version: '3.1'

networks:
  spring:

services:
  db-order:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=order
    volumes:
      - ./init-gunmarketx.sql:/docker-entrypoint-initdb.d/init-gunmarketx.sql
    ports:
      - 35432:5432

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  eureka-server:
    image: profidocker/eureka-server:1.0
    container_name: eureka-server
    ports:
      - 8761:8761
    networks:
      - spring
    depends_on:
      - zipkin

  spring-admin:
    image: profidocker/spring-admin:1.0
    container_name: spring-admin
    ports:
      - "8085:8085"
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server


